apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 891376983450.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 891376983450.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: d6c45cad
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
